### ISSUE TITLE
Updating to master causes Locale runs to break

### ISSUE THREAD

**Issue by phbprogramming** [Gab0/japonicus#124]
After merging the new changes, all locales except for max (4 in my case), run for one Epoch and then time 0.00 for all others. Only the max Locale runs normally. 

I've provided a screenshot from the web view to show what I'm talking about.

![screen shot 2018-04-11 at 1 14 21 pm](https://user-images.githubusercontent.com/5788534/38635329-a0957cc8-3d8a-11e8-89e0-69db6b99c93c.png)

**Comment by phbprogramming** [comment]
I've tried running some of the strategies generated and I'm getting a lot more than the 'minTradeNumber' parameter. Is the min trade for a selected range or for the entire dataset? This might be my issue.

**Comment by phbprogramming** [comment]
Set 'minTradeNumber' = 0

![screen shot 2018-04-11 at 1 35 18 pm](https://user-images.githubusercontent.com/5788534/38636248-45f6f44c-3d8d-11e8-85d9-140872c63059.png)

**Comment by nmikaty** [comment]
I am having the same problem since my last pull on the same date.

I'm using ```minTradeNumber: 0```, but all my locales die quickly except for one that usually lasts for several hundred epochs.

And I'm getting very poor result compared to before this pull, with very small differences between the beginning of the run and the end (800 epochs).

**Comment by jthope** [comment]
I am experiencing the same issue, even with 0 set to minTrades. 80% of the time it also fails with a "dateRange" error even though my dataset and eval_dataset spans are set to 100, and the days parameter is set to 60. If I keep the default spans to 0, it tends to error out faster with the "dateRange" exception.

**Comment by Gab0** [comment]
I made a mistake on setting locale destruction probability at 0.05 for each epoch. Thats one locale destroyed per 20 epoches on average. So this may account for early locale destruction. This part of code is being reworked.
For the 'dateRange' thing, that occours only on `-w` mode and I still don't know why. So plz avoid using `-w` until the fix... maybe all webserver graphics update scheme is badly codded.

**Comment by Gab0** [comment]
That 0 time locale run time never happened to me. 
Can the observers of the error state wich strategy is being used when this happens?

**Comment by Gab0** [comment]
Hey.. just found out. 
Early locale deletion: due to the high destruction probability I mentioned and due to population zero on them, prob due to both filters of japonicus (trade count and score). If we have two or less running locales it refuses to explode, so it runs on zero time. The new commite should provide a logging of this, and one who runs into this should paste the logs here ;)

**Comment by phbprogramming** [comment]
I am getting the error with any strategy tested, both custom strats and gekko defaults.

All locales typically run after one epoch. One Local will run through the 800 but the strategy maxes out on the second epoch no matter what.

**Comment by Gab0** [comment]
@phbprogramming gekko default strategies are guaranteed to fail like this, don't know which custom strats you are using but try RSI_BULL_BEAR.

**Comment by jthope** [comment]
Still not having luck (even with -w off). Just got latest, set 14 days on eval dataset:
![image](https://user-images.githubusercontent.com/114626/38772453-212b02f0-4005-11e8-99a8-3ec1223bc146.png)

If I run the default params in gekko I get a 19% profit, in Japonicus it finishes within 60 seconds and says no settings are profitable. I think there is still something going on.

Using this strat:
https://github.com/zschro/GekkoSchaffTrendCycle

Hardcoded stoploss and adjust false signal bits incase Japonicus had an issue with non numeric params. But that didn't appear to fix anything.

**Comment by jthope** [comment]
Update: I tried to re-run it a few times, and now its going through epoch's normally. So I think it may be random in how the parameters are initially filled?

**Comment by jthope** [comment]
Sorry for the spam, could it be related to parameters still not being resolved?
![image](https://user-images.githubusercontent.com/114626/38772615-5e7bee04-4009-11e8-881d-587c43de19f0.png)


The parameter is in the toml file. I see the above quite frequently.

**Comment by Gab0** [comment]
@jthope japonicus only considers profit above market profit. 
So if you get 30% profit while market was 50% profit, the result shown is -20%, and every individual is deleted. 
This happens for 'v3' result interpretation method, you can change it to 'v1' at Settings.py and have plain profits.
Of course this re-run thing is bizarre and checking what to change to avoid this population purge. Actually this was not supposed to happen, lets see. But the strategy seems bad anyway :/
cheers!

**Comment by jthope** [comment]
Market was -3% for my date range. Initial parameters that I entered brought it to 19%. I'm using an older version with much better results.

**Comment by Gab0** [comment]
Oh, then it should not be the case. Can you provide the main log file for some of these runs?

**Comment by nmikaty** [comment]
It seems to be working nicely again for me with RSI_BULL_BEAR_ADX strategy.
Thanks for the updates @Gab0

**Comment by xFFFFF** [comment]
@Gab0 so what mean profitv2?

**Comment by jthope** [comment]
@Gab0 is there is an option to log parameters used for each run? I think my issue really comes down to the fact that japonicus sometimes misses parameters. (ie: the missing parameter error in the logs above). This seems to happen less if I add the settings to configStrategies.py, but still happens throughout the run.

Sometimes I have some tight values for certain parameters on a strategy (ie: parameter: (1, 3)), so configStrategies.py instead of the .toml is an option I fall back to during those scenarios. If those parameters are not there for every run, then I can see why the locale is exploding so early.

**Comment by Gab0** [comment]
Hey @xFFFFF , 'v2' is a simpler 'v3'.. you can check details at  `japonicus/evaluation/gekko/backtest.py`.

@jthope The parameter reading and individue internal representation to parameters for backtest is stable, of course it may still be not due to uknown bugz.
But if a backtest is requested with missing parameters, an Exception is raised immediately and the run crashes. 
Actually it depends on strategy structure... threshold parameters used in strategy scope only can be missing, while missing indicator parameters should crash the run.
At first, try to change the interpreter thing to 'v1', and lets see if it starts working everytime... also, please paste some main logs.

**Comment by jthope** [comment]
Pulled latest code and ran it again, example log (using v3):
[bb2_adx.log](https://github.com/Gab0/japonicus/files/1925105/bb2_adx.log)

I tightened up the parameters to not leave a lot of wiggle room. But nothing profitable came back (can see in the log file). When I run random tests on the same pair in gekko (with last ~70-90 days), I get the following (5 min candles just like the japonicus backetest):

`[bbands]
TimePeriod = 20
NbDevUp = 2
NbDevDn = 2
persistence_upper = 3
persistence_lower = 3`
![image](https://user-images.githubusercontent.com/114626/38948069-7c4a7292-430c-11e8-9e13-8b201c4e2565.png)

`[bbands]
TimePeriod = 20
NbDevUp = 4
NbDevDn = 1
persistence_upper = 3
persistence_lower = 5`
![image](https://user-images.githubusercontent.com/114626/38948148-acf218d2-430c-11e8-8806-61155d4f9b14.png)

The ADX indicator is hard coded with the default settings to make this test easier.

If I pull v0.56 down, I start to see profitable strat params (in v3 profit mode). This latest build pops the locales too soon I think. There are several profit variations but it does not seem to find them even with the tightened parameters. 

I've also used this setting in both v0.56 and v0.58:
![image](https://user-images.githubusercontent.com/114626/38948347-545adcf8-430d-11e8-8439-3864eb6fa8be.png)


While I know the strat is very simple (BB+ADX). Gekko shows several profitable scenarios over a course of 70-90 days. Japonicus v0.58 does not and finishes the run within minutes.

Am I missing something?

**Comment by Gab0** [comment]
@jthope Oh, I'm seeing what happened. You exposed the most subversive bug ever on the history of japonicus ;c (maybe).
With negative sharpe, a positive profit turns into a negative or very low score as the score is calculated as profit * pweigth * (1+ sharpe * pweight).  This affects each individual with good profit but negative sharpe.
This is not guaranteed to be the cause, I'm remaking the evaluation functions. 
If you want to prove this point now just test with sharpe weigth as zero and see if things get normal.
cheers!

**Comment by Gab0** [comment]
I wonder why such result got negative sharpe? 
There was a lot of trades (200+) but if we are going to consider sharpe on score maybe we should accept that it was a bad score overall. Or just ignore sharpe altogether... 
To compose the new function to compute score based on profit and sharpe is being a challenge... if anyone has suggestions plz report in.

**Comment by phbprogramming** [comment]
There is a noted bug in Gekko. Sharpe values are not calculated correctly. Probably not a good idea to evaluate with them until this gets fixed.

**Comment by Gab0** [comment]
@phbprogramming I thought the fix was already included at the branches already.. mine is fixed. 
Maybe that accounts for that strange sharpe @jthope .

**Comment by jthope** [comment]
I'm using the dev branch so I'm not sure if its still bugged in Gekko. However, I just tested with sharpe to 0, and no change. I also tested v1, v2, v3 modes again. minTradeNumber set to 0.

![image](https://user-images.githubusercontent.com/114626/38956661-45a0fd96-4326-11e8-87db-fad23371d516.png)

-g and -gc modes both affected. I've never gotten -b to work.

Anything else I should look at?

**Comment by Gab0** [comment]
@jthope Function is fixed here at master branch, but you still have issues with `wsharpe=0`, so that should be o no use.
You restrained your data to last 70 days, but is deltaDays at 60 days or something? With low delta days the results would be really different indeed.

**Comment by jthope** [comment]
I played around with various ranges to debug. Using a span of 0, with deltaDays of any range (15, 30, 90, etc) provides the same result.

One thing I do notice, is that the first epoch always generates 0 trades, which is impossible for this spammy strat:
![image](https://user-images.githubusercontent.com/114626/38957103-a02889f4-4327-11e8-9d23-f788f191cf3b.png)

What could cause that? I am using configStrategies.py to set params and not the .toml so I can have greater control over the params. I can try the toml real quick.

**Comment by jthope** [comment]
So with the .toml in strategy_parameters it works just fine. However, using configStrategies.py all the locales explode within minutes.

So I *think* that is where the issue is. Do we still have the option to use configStrategies.py? I like that for greater control over certain param strategies.

**Comment by jthope** [comment]
@Gab0 - after taking a look at the .toml vs .py settings I realized I'm dumb.

Original:
`    "BB2": {
        "bbands.TimePeriod": (20, 20),
        "bbands.NbDevUp": (2, 4),
        "bbands.NbDevDn": (2, 4),        
        "persistence_upper": (2, 5),
        "persistence_lower": (2, 5)
    },`

What it needed to be:
`    "BB2": {
        "bbands.TimePeriod": (20, 20),
        "bbands.NbDevUp": (2, 4),
        "bbands.NbDevDn": (2, 4),        
        "bbands.persistence_upper": (2, 5),
        "bbands.persistence_lower": (2, 5)
    },`

I forgot I had moved the persistence variables into the bbands object. 

All is running now. Sorry for leading this issue down the wrong path.

**Comment by Gab0** [comment]
@jthope That's nice to hear it... well wait not at all :/ Remember to share the strategy if it gets brutal results ;)
cheers!

**Comment by jthope** [comment]
Will do! Still a lot of tuning left (using diff indicators for entry/exit), and considering a dual strat. Hopefully this is the one.
